FROM nginx:1.27.0-alpine

FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80


# FROM nginx
# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY content /usr/share/nginx/html
# COPY conf /etc/nginx
# VOLUME /usr/share/nginx/html
# VOLUME /etc/nginx
# COPY ./index.html /usr/share/nginx/html/index.html